### ISSUE TITLE
Feature: Create a switch for accessing analytics of an app

### ISSUE THREAD

**Issue by siddharthlatest** [appbaseio/abc#113]
```
abc app -a|--analytics --overview|--popularsearches|--noresults|--popularfilters|--popularresults|--geoip|--latency [ID|Appname]
```

There are six different kinds of analytics that can be accessed for an app.

- [ ] Handle errors, only paid users can access analytics via token and API access.

Reference: https://documenter.getpostman.com/view/2848488/RW81vt5x#8dc72506-5bfa-4005-962d-d5455fd17009

**Comment by palash25** [comment]
PR ready for review https://github.com/appbaseio/abc/pull/119

**Comment by palash25** [comment]
This can be closed now since the PR has been merged cc @siddharthlatest
