### ISSUE TITLE
import command not building with go build -tags 'oss' ./cmd/abc/...

### ISSUE THREAD

**Issue by nguyenhmp** [appbaseio/abc#128]
Version:    0.7.1
Variant:    oss
Go version: go1.11.2
OS:         darwin
Arch:       amd64

When building with go, the import command is not available.

**Comment by octate** [comment]
Hi @nguyenhmp , `import` command is not shipped with the oss variant of abc. It's only available in the releases and !oss variant. You can download the latest release from [here](https://github.com/appbaseio/abc/releases/tag/0.7.1)
