### ISSUE TITLE
Import command doesn't exist

### ISSUE THREAD

**Issue by TheGuy68** [appbaseio/abc#129]
I've downloaded the latest version and it doesn't seem to have to import command. 
This is the output I get when trying to run the command in the import section:
"
ran: .abc import --help

USAGE
  ./abc <command> [flags]

COMMANDS
  login     login into appbase.io
  user      get user details
  apps      display user apps
  app       display app details
  create    create app
  delete    delete app
  logout    logout session
  version   show build details
  license   show project license and credits
"

**Comment by utsavoza** [comment]
Hello @TheGuy68, are you trying to build the binary locally? If so, then the built binary won't include `import` command as it is not available in abc's `oss` variant. You should be able to access the `import` command by obtaining the binaries from releases [here](https://github.com/appbaseio/abc/releases).

**Comment by siddharthlatest** [comment]
@TheGuy68 Can you verify if you downloaded a Github release? If so, which one?

**Comment by utsavoza** [comment]
@TheGuy68 Feel free to reopen the issue, if the problem persists.
