### ISSUE TITLE
Multiple collections not sync into the elasticsearch

### ISSUE THREAD

**Issue by monojitbarua** [appbaseio/abc#133]
My abc version is abc-0.8.0

Hi I have 30 different collections in mongo db. now when ever i am starting the abc api only one collection is getting inserted into elasticsearch index, not all the other collections. 

Below is the command and transform file:
./abc-0.8.0 import --transform_file="syncmongodata_file.js" --src_type=mongodb --src_uri="mongodb://localhost:27017/DB1" "http://localhost:9200/index1"

syncmongodata_file.js:
t.Source("source", source, "/.*/").Save("sink", sink, "/.*/") 

Is there anything i am missing or doing wrong? Please help me on this. 
Thanks in Advance

**Comment by utsavoza** [comment]
@monojitbarua This might happen if you are using elasticsearch version 6 or above as multiple mongodb collections will be mapped to multiple types in an index. The solution here would be to either use elasticsearch version 5 or lower or you could index each collection into a separate index. The latest abc version should allow you index multiple collections to a single index under type `_doc` by default (for v6 and above). Feel free to reopen this issue if problem persists.
