### ISSUE TITLE
import functionality has disappeared

### ISSUE THREAD

**Issue by vaughansharman** [appbaseio/abc#134]
When I run the most recent version of this tool: 0.9.0 straight from docker hub the import functionality is no longer there. I have since downloaded the binary and this does work but the docs are a bit confusing and never mention that importing doesn't work from docker.

```
USAGE
  ./abc <command> [flags]

COMMANDS
  login     login into appbase.io
  user      get user details
  apps      display user apps
  app       display app details
  cluster   display cluster details
  create    create app/cluster
  delete    delete app/cluster
  logout    logout session
  version   show build details
  license   show project license and credits

Run 'abc COMMAND --help' for more information on a command.
```

**Comment by siddharthlatest** [comment]
@vaughansharman I think I understand the issue, we setup an auto-build process which only builds the `oss` variant. @utsavoza will push a fix shortly to update this image.

**Comment by utsavoza** [comment]
@vaughansharman The docker image has been updated. You should now be able to access `import` command using the latest image.

**Comment by vaughansharman** [comment]
cheers

**Comment by sgabbiEWF** [comment]
The issue still persists..
