### ISSUE TITLE
Not Running on Mac

### ISSUE THREAD

**Issue by basementaspirations** [appbaseio/abc#138]
I downloaded the latest build of abc (abc-darwin-0.10.1) on MacOS but whenever I try to run it, I get **_command not found_** error. I added the folder to PATH but still no luck. Is there more to be done?

**Comment by siddharthlatest** [comment]
@basementaspirations No, it should just work. Even if you haven't added it to path, you can run abc by referencing the extracted executable.

If you are in the same dir, doing this should list all the available commands:

`./abc-0.10.1`

**Comment by basementaspirations** [comment]
Thats what I was missing. 

I was just writing `abc` instead of `./abc`

Thank you for your prompt help
