### ISSUE TITLE
abc import function unavailable

### ISSUE THREAD

**Issue by sgabbiEWF** [appbaseio/abc#140]
##### Checks

- [x] I have mentioned my `abc` version in the issue, if applicable.
- [x] This issue is not a duplicate.
- [x] This issue has a description.

**Comment by siddharthlatest** [comment]
@sgabbiEWF Can you please add the details?

**Comment by sgabbiEWF** [comment]
Version: 0.10.1 
I used docker to download the latest image. But when i use abc --help I do not see 'import' as one of the commands available. 

Anyone else has this issue? 

![image](https://user-images.githubusercontent.com/43061604/52795250-ae95c780-3071-11e9-81bf-7a6029bd7921.png)

**Comment by sgabbiEWF** [comment]
@siddharthlatest: Sorry I was still drafting the issue..

**Comment by siddharthlatest** [comment]
@sgabbiEWF This has been fixed now.
