### ISSUE TITLE
How to specify database and table names in import tool

### ISSUE THREAD

**Issue by gvsrini** [appbaseio/abc#142]
First le me tell you this tool is awesome.

In your example you gave the database name and table name as the same. If they are different where/how do I specify it

**Comment by jeet-parekh** [comment]
What's your data source?

**Comment by jeet-parekh** [comment]
@gvsrini, you could use the `--src_filter` parameter. It accepts regex so you could apply various filters.

**Comment by PetengDedet** [comment]
Hi @jeet-parekh and team
thanks for this great tool. I can't believe it works very fast. Awesome 👏
But can you give us an exact example to use ```--src_filter``` parameter in postgres. Since i try to use it  like this:
```shell
./abc-darwin import --src_type=postgres  --src_filter="my_table"  --src_uri="postgresql://postgres:@127.0.0.1:5432/my_db" "http://localhost:9200/my_index"
```
but still it imports all table in the database

**Comment by siddharthlatest** [comment]
@PetengDedet `src_filter` accepts a regex, and its default value is set to `.*`. You can see this here - https://github.com/appbaseio/abc/blob/c1b9147465ae3ed6172afdbe2ebac57b476a37cf/cmd/abc/appbase_import.go#L60.

You can set the flag `--test=true` which will only generate the pipeline file but not do the actual import. When you add this, what do you see in your contents for the pipeline file?

Additionally, are you using a transform file alongside? That may affect src_filter as it's possible to override this in the transform file as well.

**Comment by siddharthlatest** [comment]
Another thing you can try is specifying the tablename(s) as `--src_filter=/table1,table2/`.

**Comment by PetengDedet** [comment]
Hi @siddharthlatest thanks for the quick reply.

I just realize that in my regex will match any table_name started with ```my_table<anything>```.

Since my database has more than one table named ```my_table``` (```my_table_1```, ```my_table_backup``` it match all of these table.

So i just need to add dollar sign ```$``` at the end of the pattern and it works as expected.

For somebody in the future, having same problem, don't forget to add dollar sign at the end of the pattern 
```--src_filter=/public\.my_table$/```
