### ISSUE TITLE
abc import "postgres Heroku" to "appbase" tail issue.  Superuser

### ISSUE THREAD

**Issue by ilostit** [appbaseio/abc#143]
Hi,

I would realtime import my heroku postgres db to appbase, it's working without --tail but when i add --tail i have this issue:
 
error plucking from logical decoding pq: must be superuser or replication role to use replication slots.

Any idea ?

Thanks

**Comment by siddharthlatest** [comment]
Hi @ilostit, we explain this in our docs here https://github.com/appbaseio/abc/blob/dev/docs/importer/adaptors/postgres.md#tailing.
