### ISSUE TITLE
src_filter not working with transform_file

### ISSUE THREAD

**Issue by alesanmed** [appbaseio/abc#153]
Hi, I'm using abc version 0.10.2

When I run the following import command:
`
abc import --src_type=mongodb --src_filter=users --src_uri='mongodb://localhost:27017/db' 'http://localhost:9200/db.users'
`

Everything works as expected and only that collection is imported. But if I run the same command but adding the transform file using:
`
abc import --transform_file='/Users/user/Documents/transform.js' --src_type=mongodb --src_filter=users --src_uri='mongodb://localhost:27017/db' 'http://localhost:9200/db.users'
`

The src_filter does not work and abc imports every collection on the DB to the db.users index.

Is there something that I'm missing?

The transform.js file exists and has the following content:
```
t.Source('source', source, '/.*/')
  .Mapping({
    keyword: {
      properties: {
        my_property: { type: 'keyword' }
      }
    }
  })
  .Save('sink', sink, '/.*/');
```

I'm trying to do a mapping of _my_property_ as keyword instead of as a string.

Thank you

**Comment by alesanmed** [comment]
I'm sorry, the problem was mine. I forgot to change in the transform file the source regex. This issue can be closed.

**Comment by Xxf123abc** [comment]
still not work
