### ISSUE TITLE
Data lost when importing from mongodb

### ISSUE THREAD

**Issue by alesanmed** [appbaseio/abc#154]
abc version: 0.10.2

When I import my data from mongodb to elasticsearch and go to _discover_ tab I see that some fields in many of my documents has null values. Even the mongodb _id field is null in many documents, and for sure that every document had its _id in the database.

Also when using a transform file that takes a field from the `doc` object I get an error saying `cannot read property split of undefined`. The field name is correctly spelled and in the database is not null.

Elasticsearch version is 7.0.1 and mongodb version is 4.0.9.

Any information would be appreciated. Thank you all.

**Comment by siddharthlatest** [comment]
@alesanmed Can you try with the latest release https://github.com/appbaseio/abc/releases/tag/1.0.0-alpha.0 and let us know if it works? We added support for v7 only in this release.

**Comment by alesanmed** [comment]
Sorry for the late reply. Now it's working perfectly. Can be closed!
