### ISSUE TITLE
Sync multiple tables and join multiple tables

### ISSUE THREAD

**Issue by techpolicystore** [appbaseio/abc#177]
I'm currently using the latest docker image and cannot find in the documents how to:

1. sync different tables into appbase and avoiding conflict field names
We have to create different apps for different tables, is this the way it should be? or we can use the same app on appbase for different tables?

2. able to join different tables with transform
Still we cannot find any solution yet.

Thanks for your help.

**Comment by siddharthlatest** [comment]
@techpolicystore It's not possible to do either from within ABC. However, you can perform a JOIN and create a table based on that, and use that as the import source.
