### ISSUE TITLE
No command 'import' after compiling from source

### ISSUE THREAD

**Issue by adrianovieira** [appbaseio/abc#193]
I just compiled it from source, but the it doesn't have the command _`abc import`_

I followed your readme instruction to build it.

Are there any other _go build_ parameter which I need fill in?
What I need to do to fix the build?

##### Checks

- [x] I have mentioned my `abc` version in the issue, if applicable.
- [x] This issue is not a duplicate.
- [x] This issue has a description.

```bash
$ ./abc version
Version:    1.0.0-beta.2
Variant:    oss
Go version: go1.15.8
OS:         linux
Arch:       amd64
```

**Comment by siddharthlatest** [comment]
@adrianovieira `abc import` is currently available as part of the non oss build variant.

**Comment by siddharthlatest** [comment]
**Update:** I'm considering if we should open source the `import` command - abc isn't our top priority right now, and that would open this up for the broader community to make changes to it.

**Comment by adrianovieira** [comment]
> **Update:** I'm considering if we should open source the `import` command - abc isn't our top priority right now, and that would open this up for the broader community to make changes to it.

looking forward to it
