### ISSUE TITLE
how to login against a local elasticsearch cluster

### ISSUE THREAD

**Issue by adrianovieira** [appbaseio/abc#194]
Please, how could it authenticate against a local elasticsearch cluster for `abc import` ?

##### Checks

- [X] I have mentioned my `abc` version in the issue, if applicable.
- [x] This issue is not a duplicate.
- [x] This issue has a description.

**Comment by siddharthlatest** [comment]
@adrianovieira By login, I'm assuming you're referring to a basic auth. This should be passed as part of the URL itself for the destination. e.g. `https://user:pass@local-es:9200/dest-index`.

**Comment by adrianovieira** [comment]
yes! that is.

thx
