### ISSUE TITLE
Sub index elastic

### ISSUE THREAD

**Issue by aloysius-tim** [appbaseio/abc#196]
Hi there,

Thanks for your amazing work guys ! Been looking for this for a long time and will have it in production soon.

Sync (--tail) is working very well, but I'd like to create different indexes for the same table:

index_2020 for rows of 2020
index_2021 for rows of 2021 etc...

Is there any way to do that ? I was thinking it would be easy to do so with the transformers, but is there any way to get the data input dynamically at this stage ?

```
t.Source("source", source, "/search.clients")
 .Transform(rename({ field_map: { "id": "_id" } }))
 .Transform(omit({"fields":["_version"]}))
 .Save("sink", sink, "/.index_2020/") // When saving dynamic index depending on the row date
```

Thanks for your help and your work on ABC

Tim

##### Checks

- [X] I have mentioned my `abc` version in the issue, if applicable.
- [X] This issue is not a duplicate.
- [X] This issue has a description.

**Comment by siddharthlatest** [comment]
This is possible with the latest release. Example here: https://github.com/appbaseio/abc/blob/dev/docs/importer/examples.md#importing-to-a-different-destination-index
