### ISSUE TITLE
import panic: runtime error

### ISSUE THREAD

**Issue by xuhuanzy** [appbaseio/abc#205]
Windows abc-1.0.0-beta.3 
abc import 
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0xa111bd]

goroutine 1 [running]:
main.main()
        E:/PostgreSQL/abc-1.0.0-beta.3 /cmd/abc/main.go:41 +0x9d

Windows abc-1.0.0-beta.2 no panic

**Comment by siddharthlatest** [comment]
@xuhuanzy Thanks for bringing up the issue. There was an issue with the earlier build assets, this should be addressed now.

**Comment by AdamCuiYH** [comment]
same with you @xuhuanzy ,I still got the problem, my bac version is 1.0.0-beta.3.when i input "abc version" in the command ,it's ok,but when i input "abc import",i got the same error as yours，so how to solve this?
