### ISSUE TITLE
Enhancement: abc app <app_name>

### ISSUE THREAD

**Issue by siddharthlatest** [appbaseio/abc#60]
In addition to showing

```
ID:         6875
Name:       appbase-fun
ES Version: 2.4
```

- [x] We can also show `Created At` date, `Owner`, `Users`.

- [x] When using `--metrics` switch, we can use a more verbose date format, perhaps, yyyy-MMM-dd (2017-Jul-04)

**Comment by aviaryan** [comment]
> When using --metrics switch, we can use a more verbose date format, perhaps, yyyy-MMM-dd (2017-Jul-04)

With `--metrics`, metrics will be only shown from the start of the current month. So I think the year is redundant there. Views?

**Comment by siddharthlatest** [comment]
@aviaryan Currently we are showing all the metrics with --metrics. In this case, showing yyyy is important.

![](https://i.imgur.com/Hdq5Nrt.png)
