### ISSUE TITLE
Open an app's data view

### ISSUE THREAD

**Issue by aviaryan** [appbaseio/abc#66]
```sh
abc app APP  --open
```

Mirage's implementation of Dejavu URL: https://github.com/appbaseio/mirage/blob/f3ea668f57ffe25fd0da55dc380667d51cbcd1ab/app/shared/urlShare.ts#L18

**Comment by siddharthlatest** [comment]
@aviaryan Thinking to change the option name so we can also have similar commands to open the `query view` and `mappings view`.
