### ISSUE TITLE
Duplicated Results

### ISSUE THREAD

**Issue by luanmuniz** [appbaseio/abc#80]
**abc version**: 0.5.0
**Adaptor**: Postgres
**Transforms**: None
**cli command**: `abc import --src_type="postgres" --src_uri="postgres"  --replication_slot="standby_replication_slot" "https://elasticsearch/twitter"`

Basically, i'm having duplicated entries when syncing databases. What informations do you guys need?

**Comment by siddharthlatest** [comment]
Hey @luanmuniz, is there a dataset (or subset) where this can be replicated? A .CSV file would be great.

**Comment by luanmuniz** [comment]
I think it was the `tail: true`. I was not using that and resetting the application.
