### ISSUE TITLE
Is it possible to make parent joins work?

### ISSUE THREAD

**Issue by aguyinmontreal** [appbaseio/abc#81]
Hi!

Does ABC support the new parent joins (since parent/child relationships are deprecated)?  (see https://www.elastic.co/guide/en/elasticsearch/reference/current/parent-join.html )

If yes, how can I make it work (duplicating from MongoDB to ElasticSearch)?

Thank you!

##### Checks

- [X ] I have mentioned my `abc` version in the issue, if applicable.
- [ X] This issue is not a duplicate.
- [ X] This issue has a description.

**Comment by siddharthlatest** [comment]
Hey @aguyinmontreal, it should be possible. We support providing a custom mapping object. See here - https://github.com/appbaseio/abc/blob/dev/docs/importer/transform_file.md.
