### ISSUE TITLE
Add a healthcheck layer to the docker image

### ISSUE THREAD

**Issue by a-magdy** [appbaseio/abc#83]
Hi,

I am trying to use `appbaseio/abc:0.5.0` instead of mongo-connector

and I think it would be nice if the image contains a healthcheck option, so that the containers start in the write order, I know it is a bit tricky to do it with a connector app .. but I am looking for something basic, like if the app crashed on start, or the there is a problem with configuration, authentication or whatever, I can stop other containers from running as well

I did something similar with mongo-connector, but I am not sure how to add it to the current Dockerfile in abc

My implementation in mongo-connector: https://github.com/Quadric/mongo-connector-docker/blob/2.5-es_2.4.1/Dockerfile

Which basically reads the timestamp file, looking for the replica-set name in it, if not then the app failed to start

##### Checks

- [x] I have mentioned my `abc` version in the issue, if applicable.
- [x] This issue is not a duplicate.
- [x] This issue has a description.

**Comment by siddharthlatest** [comment]
This is available now via the `--verify` switch.
