### ISSUE TITLE
Problem with importing from postgresql.

### ISSUE THREAD

**Issue by Gizzio** [appbaseio/abc#85]
It is impossible to import tables which names contain upper case.

From postgres log:
`ERROR:  relation "public.tablename" does not exist at character 15
STATEMENT:  SELECT * FROM public.TableName
`

From abc import log:
`panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xb45c80]

goroutine 55 [running]:
sync.(*RWMutex).RLocker(...)
	/Users/siddharthlatest/.gvm/gos/go1.9/src/database/sql/sql.go:2441
database/sql.(*Rows).Next(0x0, 0xc420514150)
	/Users/siddharthlatest/.gvm/gos/go1.9/src/database/sql/sql.go:2441 +0x30
github.com/appbaseio/abc/private/adaptor/postgres.(*Reader).iterateTable.func1(0xc420452240, 0xc4204521e0, 0xc420017125, 0x3, 0xc420442280, 0xc42001ea20)
	/Users/siddharthlatest/.gvm/pkgsets/go1.9/global/src/github.com/appbaseio/abc/private/adaptor/postgres/reader.go:150 +0x935
created by github.com/appbaseio/abc/private/adaptor/postgres.(*Reader).iterateTable
	/Users/siddharthlatest/.gvm/pkgsets/go1.9/global/src/github.com/appbaseio/abc/private/adaptor/postgres/reader.go:104 +0x91
`

My abc version is 0.5.0.

**Comment by baderth** [comment]
Unquoted identifiers are folded to lowercase by PG, so put your camelCase tablename into "quotes"
