### ISSUE TITLE
Import : Error 413 (Request Entity Too Large)

### ISSUE THREAD

**Issue by kanrio** [appbaseio/abc#86]
**Version:    0.5.0
Variant:    !oss
Go version: go1.9
OS:         windows
Arch:       amd64**

`abc import --src_type=mongodb --src_filter=Product --src_uri="mongodb://localhost:27017/db" "https://username:password@scalr.api.appbase.io/appName"`

Using the above command gives this result : 

> 980 total data record(s) indexed
> [31mERRO[0m[0004] elastic: Error 413 (Request Entity Too Large)  [31mversion[0m=2 [31mwriter[0m=elasticsearch
> [31mERRO[0m[0004] elastic: Error 413 (Request Entity Too Large)  [31mname[0m=sink [31mpath[0m="source/sink" [31mtype[0m=elasticsearch
> 1960 total data record(s) indexed
> [31mERRO[0m[0009] elastic: Error 413 (Request Entity Too Large)  [31mversion[0m=2 [31mwriter[0m=elasticsearch
> [31mERRO[0m[0009] elastic: Error 413 (Request Entity Too Large)  [31mversion[0m=2 [31mwriter[0m=elasticsearch
> 2940 total data record(s) indexed
> [31mERRO[0m[0014] timeout reached waiting for Out channels to clear
> [31mERRO[0m[0014] elastic: Error 413 (Request Entity Too Large)  [31mversion[0m=2 [31mwriter[0m=elasticsearch
> [31mERRO[0m[0014] elastic: Error 413 (Request Entity Too Large)  [31mversion[0m=2 [31mwriter[0m=elasticsearch
> 3920 total data record(s) indexed
> [31mERRO[0m[0015] elastic: Error 413 (Request Entity Too Large)  [31mversion[0m=2 [31mwriter[0m=elasticsearch

The Product collections have only 40k records with 16 fields each record
I made other imports more than 80k but lesser fields around 4-8 fields and works fine.

Any idea ?

**Comment by kwiatdiamonds** [comment]
Any update as to how you resolved this issue?

**Comment by siddharthlatest** [comment]
@kwiatdiamonds This can now be controlled using the `--bulk_requests` and `--request_size` params.

**Comment by sagardere** [comment]
In my case i am adding  "**--request_size=500000**" Option, My problem solve. Thank You.

> ./abc-0.6.6 import --src_type=json --src_uri="./1KWJewelrySerialData.json" --typename=JewelrySerialData --transform_file="./jewelry_Serial.js" **--request_size=500000** --log.level="error" https://rYndNrRZ2:ef673381-32d2-43@scalr.api.appbase.io/elastic-application
