### ISSUE TITLE
Mongo DB 3.6 to elasticsearch 6 index creation issue : if db hase more than 1 collection only one collection index is creating

### ISSUE THREAD

**Issue by gsmtamil** [appbaseio/abc#87]
abc details:

Version:    0.5.0
Variant:    !oss
Go version: go1.9
OS:         windows
Arch:       amd64

**Test Case 1:   
mongo database with multiple collections
Elastic search 6
creating index using abc :  it is creation index only once collection** 

Test Case 2:   
mongo database with collection one
Elastic search 6
creating index using abc : working fine

Test Case 3:   
mongo database with collection one
**Elastic search 5**
creating index using abc : working fine

Test Case 4:   
mongo database with multiple collections
**Elastic search 5**
creating index using abc : working fine

##### Checks

- [1 ] I have mentioned my `abc` version in the issue, if applicable.
- [x] This issue is not a duplicate.
- [ 1] This issue has a description.

**Comment by siddharthlatest** [comment]
@gsmtamil That may be because starting Elasticsearch 6, there is only type allowed per index. What you may want to do is map one collection to one index.

**Comment by gsmtamil** [comment]
Thanks for your time @siddharthlatest 

It might helpful if this option **(map one collection to one index)** is available like 
--colname "collection-name" or some other way.

Example :  
abc import --src_type=mongodb -t --src_uri="mongodb://USER:PASS@HOST:PORT/DB" --colname="collection-name" "https://USER:PASS@scalr.api.appbase.io/APPNAME"

**Comment by jeet-parekh** [comment]
@gsmtamil, the `--src_filter` parameter would help you here. It accepts regex so you could apply various filters.

**Comment by S-Cardenas** [comment]
I'm leaving this here in the hopes that it will help people who are trying to create multiple indices for each mongo collection (or postgres table). It's part of the shell script I use to write each postgres table to an individual index.

`
### Use this code for N index indices ###
#########################################
declare -a arr=("users" "data_stories" "facts" "publishers") # Our tables which will be indexed
arr_length=${#arr[@]}
iter=1
abc_command=""

elasticsearch="elasticsearch"
elasticport="9200"
postgresport="5432"

# Create a replication slot for each table
for i in "${arr[@]}"
  do

    if PGPASSWORD=$FACTS_MACHINE_DATABASE_PASSWORD psql -h "$FACTS_MACHINE_DATABASE_URL" -U "$FACTS_MACHINE_DATABASE_USERNAME" -c "SELECT * FROM pg_replication_slots;" | cut -d \| -f 1 | grep -qw "$i"; then
      echo "The replication slot already exists for $i. No need to create it."
    else
      echo "Replication slot doesn't exist yet. Let's create the replication slot for $i."
      psql -h "$FACTS_MACHINE_DATABASE_URL" -U "$FACTS_MACHINE_DATABASE_USERNAME" -d "$FACTS_MACHINE_DATABASE_NAME" -c "select * from pg_create_logical_replication_slot('$i', 'test_decoding');"
    fi

    if [ $iter = $arr_length ]
    then
      abc_command+="abc import --src_type=postgres --src_filter=$i -t --replication_slot='$i' --src_uri='postgresql://${FACTS_MACHINE_DATABASE_USERNAME}:${FACTS_MACHINE_DATABASE_PASSWORD}@${FACTS_MACHINE_DATABASE_URL}:${postgresport}/${FACTS_MACHINE_DATABASE_NAME}' 'http://${elasticsearch}:${elasticport}/$i'"
    else
      abc_command+="abc import --src_type=postgres --src_filter=$i -t --replication_slot='$i' --src_uri='postgresql://${FACTS_MACHINE_DATABASE_USERNAME}:${FACTS_MACHINE_DATABASE_PASSWORD}@${FACTS_MACHINE_DATABASE_URL}:${postgresport}/${FACTS_MACHINE_DATABASE_NAME}' 'http://${elasticsearch}:${elasticport}/$i' & "
    fi

    iter=$(expr $iter + 1)
done

echo "Checking to see if ElasticSearch is up and running."

until curl ${elasticsearch}:${elasticport}/_cluster/health?pretty 2>&1 | grep status | egrep "(green|yellow)"; do
  printf '.'
  sleep 1
done

echo "ElasticSearch is up and running!"
echo "Now trying to sync Postgres with ElasicSearch"

eval $abc_command
`
