### ISSUE TITLE
certificate signed by unknown authority when running abc

### ISSUE THREAD

**Issue by vaughansharman** [appbaseio/abc#88]
This happens with both the binary and docker version

run
`login google`

and get
```
Checking token ERRO[0015] Get https://accapi.appbase.io/user: x509: certificate signed by unknown authority
```

**Comment by siddharthlatest** [comment]
@vaughansharman Thanks for reporting the issue, I can verify it.

The root cause is that we were missing some intermediate CA related certificates that are required by non-browser clients.

I have already applied a fix and it should be resolved.
